- Sources/API/Converter.swift
- Sources/Document/CRDT/Primitive.swift
- Tests/Document/CRDT/PrimitiveTests.swift
- When converting primitive values to a byte stream,  apply network byte order(Big endian)
- Trim the less than a millisecond in Date primitive value
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Support Network byte order for Primitive values

- Sources/Document/Document.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONObject.swift
- Tests/Document/JSONObjectTests.swift
Remove features for ```dynamicMemberLookup``` from JSONObject
We faced that the references of class instances using generics should be held in JsonArray.
We decided to provide a simple interface first, even though many issues have been resolved and can resolve the above issue. Because new issues keep coming up.
So, removed features for ```dynamicMemberLookup``` from JSONObject
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove features for dynamicMemberLookup from JSONObject

- Sources/Document/CRDT/RGATreeList.swift
- Sources/Document/Change/Change.swift
- Sources/Document/Change/ChangePack.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Time/TimeTicket.swift
- Tests/Document/DocumentConcurrentAccessTests.swift
- Tests/Document/DocumentTests.swift
- Tests/Document/JSONArrayTests.swift
- Tests/Document/JSONObjectTests.swift
- Yorkie.xcodeproj/project.pbxproj
Remove redundant codes
Change Document from class to actor for concurrent access to it.
Remove some redundant codes.
Change TimeTicket/lamport and delimiter from var to let
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Change Document from class to actor for concurrent access to it

- Sources/Document/Change/Change.swift
- Sources/Document/Change/ChangePack.swift
- Sources/Document/Document.swift
- Sources/Document/Operation/AddOperation.swift
- Sources/Document/Operation/MoveOperation.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Operation/SetOperation.swift
- Tests/Document/Change/ChangeTests.swift
- [Change the type of ChangePack from class to struct](https://github.com/yorkie-team/yorkie-ios-sdk/commit/4eb4b93612ceb4db80d975c2ecc382b7b41e10a3)
- [Change types of Change and Operations from class to struct](https://github.com/yorkie-team/yorkie-ios-sdk/commit/a50a4a9898a0bed8960350af16651a2431676130)
ChangePack and the members included in it are used by Client. It may cause data racing.
The above types need not be ``class``. It would be better to be a ``struct`` to avoid data racing.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Change some types from class to struct to avoid data racing

- Sources/API/Converter.swift
- Sources/Document/CRDT/Primitive.swift
- Tests/Integration/ClientIntegrationTests.swift
- Improve the client auto sync test to check all primitive types.
-  Specify Date rawValue type to Int64
- Add utility function "trimedLessThanMilliseconds"
- In Yorkie system, the Date primitive value is represented as milliseconds Int64.
- In iOS, the Date value is represented as seconds Double.
- So, the date value in iOS has to trim less than milliseconds to transmit and compare values.  
Fixes #
- Date.trimedLessThanMilliseconds is required, to compare the iOS Date structure with the Yorkie Date primitive value.
```release-note
```
```docs
```
**Checklist**:
> Improve Document sync Test.

- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Document/Util/JSONObjectable.swift
- Tests/Document/JSONObjectTests.swift
- Tests/Document/Util/YorkieJSONObjectableTests.swift
- Yorkie.xcodeproj/project.pbxproj
[Add get(keyPath:) to JSONObject](https://github.com/yorkie-team/yorkie-ios-sdk/commit/70bc1af1b92bb1eadf2c50a1f76cd0f1e9ddc5da)
- I arbitrarily used `/.^/` for key separator. It should be changed to something suitable.
[Rename YorkieJSONObjectable to JSONObjectable](https://github.com/yorkie-team/yorkie-ios-sdk/commit/838f6db7a6bd82b72a9bed5c71dd762e93d6f490)
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add get(keyPath:) to JSONObject

- Sources/Core/Client.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Unit/Core/ClientTests.swift
- Tests/Unit/Document/DocumentTests.swift
Change eventStream of Client from Error to Never
- It simplifies the interface of `Client.eventStream.sink`
Change labels of Document.update
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Change eventStream of Client from Error to Never

- Sources/Core/Client.swift
- Sources/Core/Logger.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/ClientTests.swift
- Tests/Integration/CounterIntegrationTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Implements the TLS connection.
- If the port is 443, the client tries to connect the server with TLS support.
- Change the channel API from GRPCChannelPool to ClientConnection Builder.
- No need for "try-catch" blocks for client init() anymore.
- Add channel clean-up.
- Enable ClientTest TC.
- Change the error message to a more informative one.
After
```
2022-12-20T16:12:18+0900 error Yorkie : [Yorkie/Client.swift:229] activate() - Failed to request activate client(-[ClientTests test_activate_and_deactivate_client_with_key]-2022-12-20 07:12:18 +0000).(Invalid HTTP response status: 464)
```
Before
```
2022-12-20T16:13:46+0900 error Yorkie : [Yorkie/Client.swift:229] activate() - Failed to request activate client(-[ClientTests …
```
> Implements the TLS connection.

- Sources/API/Converter.swift
- Sources/API/V1/Protos/resources.proto
- Sources/API/V1/resources.pb.swift
Remove duplicated key from TextNodeAttr.
Since TextNode.attributes have keys, this commit removes key from TextNodeAttr.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove duplicated key from TextNodeAttr

- Sources/Document/CRDT/CRDTCounter.swift
- Sources/Document/CRDT/Primitive.swift
- Sources/Document/Json/JSONCounter.swift
- Sources/Document/Util/YorkieCountable.swift
- Tests/Integration/CounterIntegrationTests.swift
- Tests/Unit/Document/DocumentTests.swift
- Change Counter increase() to accept any numeric value
- Now accepts any Integer values.
- Floating-point values are cast to integer values (eg. 3.5 => 3)
- Int type converted to long primitive type.
- JSONCounter doesn't throw errors.
- Add Counter Test Codes.
- overflow
- floating-point value.
Fixes #
```release-note
do-try-catch is no longer required when calling increase().
```
```docs
```
**Checklist**:
> Change Counter increase() to accept any numeric value

- Sources/Core/Client.swift
- Sources/Util/Errors.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/ClientTests.swift
- Tests/Integration/CounterIntegrationTests.swift
- Tests/Integration/TextIntegrationTests.swift
- Tests/Unit/Document/JSONObjectTests.swift
This PR is the same as the issue https://github.com/yorkie-team/yorkie-js-sdk/pull/440 in JS.
- Client.attach() wait until the attached document has been initialized or timed out.
- The default timeout is 5 sec.
-  Due to the sync duration being 1 sec, Change the delay time for document sync in Test Codes from 1 sec to 1.5 sec.  
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Let Client.attach wait until stream initialization is finished

- Sources/Core/Auth.swift
- Sources/Core/Client.swift
Add x-shard-key to APIs
Fixes #70 
Related to https://github.com/yorkie-team/yorkie/pull/499
> Add x-shard-key to APIs

- Examples/TextEditorApp/TextEditorApp/TextEditor/TextViewModel.swift
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/Json/JSONText.swift
- Tests/Unit/Document/JSONTextTest.swift
- Tests/Unit/Util/Helper.swift
- Replace event stream of Text(onChange) with Document.subscribe
- Hide TextChange class
Fixes #79 
The target branch will be changed to main after previous PR merged.
```release-note
The event Stream of Text was removed. Use Document.subscribe instead.
```
```docs
```
**Checklist**:
> Replace Text event Stream with Document.subscribe 

- .github/workflows/swift-integration.yml
- .github/workflows/swift.yml
- Examples/KanbanApp/KanbanApp/Kanban/KanbanViewModel.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/TextViewModel.swift
- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/Change/Change.swift
- Sources/Document/DocEvent.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONText.swift
- Sources/Document/Operation/AddOperation.swift
- Sources/Document/Operation/EditOperation.swift
- Sources/Document/Operation/IncreaseOperation.swift
- Sources/Document/Operation/MoveOperation.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Operation/SelectOperation.swift
- Sources/Document/Operation/SetOperation.swift
- Sources/Document/Operation/StyleOperation.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/DocumentIntegrationTests.swift
- Tests/Unit/Document/CRDT/CRDTRootTests.swift
- Tests/Unit/Document/DocumentTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- Tests/Unit/Util/Helper.swift
- provide a new API that allows users to subscribe to the document with a specific target path.
- improve the event value of Local/RemoteChange.
Fixes #74 #76 
```release-note
document.eventStream is removed. Use document.subscribe() to catch the events.
Please refer to the samples.
```
```docs
```
**Checklist**:
> Allow specifying a topic when subscribing to a document

- Sources/Document/Change/Change.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Util/LLRBTree.swift
- Tests/Unit/Document/DocumentTests.swift
- Tests/Unit/Document/JSONObjectTests.swift
- Add getValueByPath() to the document. (https://github.com/yorkie-team/yorkie-js-sdk/pull/487)
- Modify API exposures to match JS API
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add getValueByPath() to the document 

- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONTree.swift
- Tests/Integration/GCTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- Yorkie.xcodeproj/project.pbxproj
- Fix gc to remove all removed nodes
- remove unnecessary code (no need to traverse indexTree)
- https://github.com/yorkie-team/yorkie-js-sdk/pull/568
- Add TC for garbage collection.
- Fix JSON string of  JSONText Attributes.
- Add remove function to JSONArray.  
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix gc to remove all removed nodes

- Sources/API/Converter.swift
- Tests/Integration/ClientIntegrationTests.swift
- Fix converter to get tree from snapshot
- Convert pbElement to JSONTree codes are missing.
- adding TC for the snapshot.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix converter to get tree from snapshot

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- This is the Swift implementation of JS PR below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/639
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add toJS to return TreeNode of Tree

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RGATreeSplit.swift
- Sources/Util/LLRBTree.swift
- Sources/Util/SplayTree.swift
- Sources/Util/Trie.swift
- Remove memory leaks caused by strong reference cycles of Trees.
- Set parents as weak to prevent a strong reference cycle. 
- Set prev and next of RGATreeSplit too.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove strong reference cycle

- Sources/Document/Document.swift
- Tests/Integration/GCTests.swift
- This is the Swift implementation of JS PR below
-https://github.com/yorkie-team/yorkie-js-sdk/pull/644
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add DisableGC option to document

- Sources/API/Converter.swift
- Sources/API/V1/yorkie/v1/resources.pb.swift
- Sources/API/V1/yorkie/v1/resources.proto
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/RGATreeSplit.swift
- Sources/Document/Json/JSONText.swift
- Sources/Document/Operation/StyleOperation.swift
- Tests/Integration/TextIntegrationTests.swift
- Tests/Unit/Document/DocumentTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- This is the Swift implementation of JS PR below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/642
- Port every TC for Text from JS.
- toSortedJSON() of JSONText returns sorted attributes too. 
- change var name "plainText" of JSONText to "toString" to match the name of JS
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Support concurrent formatting of Text

- Sources/Util/LLRBTree.swift
- Fix misused generic declaration.
- It has no problem now. but could be an error with Swift 6
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix generic warning at Xcode 15

- Sources/Document/Document.swift
- Sources/Document/Operation/SetOperation.swift
- Tests/Integration/GCTests.swift
- Tests/Unit/Document/DocumentTests.swift
- This is the Swift implementation of JS PR below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/676
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix missing collection of removed elements from the root

- Sources/Document/Json/JSONTree.swift
- Tests/Unit/Document/JONSTreeTests.swift
- Add toJSONString to JSONTreeNode, so The user can get the changes by operations. 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add toJSONString to JSONTreeNode

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Util/String+Extensions.swift
- Tests/Unit/Document/CRDT/CRDTTreeTests.swift
- Tests/Unit/Document/JONSTreeTests.swift
- By the JSON spec. special characters must be escaped with a slash. (eg. newline => \n) (https://www.json.org/json-en.html)
- The toJSON in JSON Node makes JSON string without escaping now. So toJSON string can't be parsed. 
- eg. JSONTreeTextNode(value: "\n").toJSONString
```
{"type": "text", "value": "
"}
```
- I added toJSONString var in String Extension. And explicitly escape the string in toJSONString.
- I also apply a similar modification to the CRDTTree.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Escape the string during toJSON.

- Sources/Document/CRDT/CRDTText.swift
- Sources/Util/Dictionary+Extension.swift
- Tests/Integration/TextIntegrationTests.swift
- To prevent escaping shahs of URL.
- eg. (http://abc.def -> http:\\/\\/abc.def)
- apply "withoutEscapingSlashes" option when encoding dictionaries to JSON  
- I also made changes to the TCs. 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Prevent escaping slash of URL

- Examples/KanbanApp/KanbanApp/Kanban/View/KanbanViewController.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/View/TextEditorViewController.swift
- In Swift 5.5, UIKit and Swift UI components are all **`@MainActor`**
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove unused @MainActor

- Sources/Document/Json/JSONTree.swift
- Tests/Unit/Document/JONSTreeTests.swift
- docker/docker-compose-ci.yml
- docker/docker-compose.yml
- Fix the Incorrectly generated attributes for toJsonString  of Tree
The attributes of Tree node are contained as json String.
When initialize the JSONTreeNode, the json String converted to dictionary by toJSONObject in String+Extension.
https://github.com/yorkie-team/yorkie-ios-sdk/blob/ca1fbc01690ba9bd21c205d9916ef7d9ae956dd9/Sources/Util/String%2BExtensions.swift#L41-L47
The "jsonObject" that "JSONSerialization.jsonObject()" creates contains foundation types. (NSNumber, NSString...)
Since "jsonObject" isn't Encodable, they can't converted to string by old logic.
So I added JSONSerialization.data() to convert them to string. 
Fixes #
**Does this PR introduce a user-facing …
> Fix the Incorrectly generated attributes for toJsonString  of Tree

- Sources/Document/CRDT/Primitive.swift
- Sources/Document/Json/JSONObject.swift
When performing a Primitive deepcopy, the absence of removedAt led to a problem where deleted elements reappeared. This PR addresses the issue by making sure that removedAt is included in the primitive deepcopy.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add missing removedAt during Primitive deepcopy

- Sources/Core/Client.swift
- Tests/Integration/ClientIntegrationTests.swift
Previously, when using `resume`, remote changes made during the `pause` were not being applied. After resuming, if there have been any local or remote changes, a sync is triggered, and previous changes are applied.
This PR addresses this issue by triggering a sync during `resume`.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add forced sync when switching to realtime mode

- Sources/Document/CRDT/CRDTRoot.swift
- Tests/Integration/GCTests.swift
- Yorkie.xcodeproj/project.pbxproj
- iOS implementation for the corresponding JS PR
- https://github.com/yorkie-team/yorkie-js-sdk/pull/714
- 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix getGarbageLen to retrun correct size 

- Sources/API/V1/yorkie/v1/yorkie.pb.swift
- Sources/API/V1/yorkie/v1/yorkie.proto
- Sources/Core/Client.swift
- docker/docker-compose-ci.yml
- docker/docker-compose.yml
iOS implementation for the corresponding JS PR
- https://github.com/yorkie-team/yorkie-js-sdk/pull/726
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Reflect interface changes of server DB sharding

- .swiftlint.yml
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Tests/Integration/TreeIntegrationTests.swift
Fix invalid `TreeChange`s in concurrent `Tree.Style`
Related to https://github.com/yorkie-team/yorkie-android-sdk/pull/149
```release-note
```
```docs
```
**Checklist**:
> Fix invalid TreeChanges in concurrent Tree.Style

- Sources/Util/LLRBTree.swift
- Correct incorrectly ported code.
- Set "inout" for the Node parameter to apply changes.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix llrb tree error

- Sources/API/V1/yorkie/v1/yorkie.pb.swift
- Sources/API/V1/yorkie/v1/yorkie.proto
- Sources/Core/Client.swift
- docker/docker-compose-ci.yml
- docker/docker-compose.yml
- https://github.com/yorkie-team/yorkie-js-sdk/pull/740
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Restore interface changes due to server DB sharding

- Sources/Core/Client.swift
- Tests/Integration/ClientIntegrationTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/759
Fixes #
- Change the "Attachment" from struct to class to prevent copying when it is passed via function parameter.
- Since the sync() can't run without waiting, The added TC can't make an issue situation.
```release-note
```
```docs
```
**Checklist**:
> Prevent remote-change events from occurring in push-only mode

- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONText.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/TreeSytleOperation.swift
- Sources/Util/Dictionary+Extension.swift
- Sources/Util/String+Extensions.swift
- Tests/Integration/IntegrationHelper.swift
- Tests/Integration/TreeIntegrationTests.swift
- Tests/Unit/Document/JONSTreeTests.swift
- Fix incorrect string value return of Tree Node style operation. (eg. "text" is returned as "\"text\"") 
- Refactor attribute managing logics.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix string style value error of Tree Node attributes 

- Sources/Document/Document.swift
DocEvent should be emitted synchronously with applying changes.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> remove async call of subscribe callbacks

- .github/workflows/add-release-assets.yml
- .github/workflows/gh-pages.yml
- .github/workflows/swift-integration.yml
- .github/workflows/swift.yml
- Sources/API/Converter.swift
- Sources/API/V1/yorkie/v1/resources.pb.swift
- Sources/API/V1/yorkie/v1/resources.proto
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RHT.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Operation/TreeSytleOperation.swift
- Sources/Document/Time/TimeTicket.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/TreeIntegrationTests.swift
- Tests/Unit/Document/CRDT/RHTTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- Implement Tree.RemoveStyle
- https://github.com/yorkie-team/yorkie-js-sdk/pull/745
-  https://github.com/yorkie-team/yorkie-js-sdk/pull/755
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Implement Tree.RemoveStyle

- Sources/Document/CRDT/CRDTTree.swift
- Tests/Integration/TreeIntegrationTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/774
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Reverse TreeChanges when Deleting in Tree

- Sources/Core/Client.swift
- Tests/Unit/Util/URLTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Added functionality so that commonly used URLs can be used to create a client
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add Client constructor support URL address

- Sources/Document/Change/Change.swift
- Sources/Document/Document.swift
- Tests/Integration/PresenceTests.swift
- Fix missing my presence info after updating the document.
- Refactor Document.update() to same as JS.
- Add a excludeMyself parameter to the getPresences()
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix presence issues.

- Sources/API/Converter.swift
- Sources/API/V1/yorkie/v1/resources.pb.swift
- Sources/API/V1/yorkie/v1/resources.proto
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RGATreeSplit.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Operation/TreeSytleOperation.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/803
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Handle concurrent editing and styling in Tree

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RHT.swift
- Tests/Integration/TreeIntegrationTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/804
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix invalid tree style changes

- .github/workflows/swift-integration.yml
- Sources/Core/Client.swift
- Sources/Document/Change/ChangeContext.swift
- Sources/Document/Json/JSONTree.swift
- Tests/Integration/TreeConcurrencyTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Yorkie.xcodeproj/xcshareddata/xcschemes/Yorkie.xcscheme
- https://github.com/yorkie-team/yorkie-js-sdk/pull/792
- remove syncShutdownGracefully() in Client.
- syncShutdownGracefully() caused hangs when performing Tree concurrent tests.
- close connections are performed with rpcClient.channel.close() so, It's redundant.
- Create some deepcopy() function to classes.
- The initial Tree root is used repeatedly with the Tree concurrent test.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add Tree concurrency tests

- Sources/Document/CRDT/CRDTTree.swift
- RHT that storing attributes is shallowly copied, So the style set does not perform at yorkie tree.
- Remove unnecessary code.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix process of tree style change

- Sources/API/Converter.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Util/IndexTree.swift
- Tests/Unit/API/V1/ConverterTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/836
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix incorrect tree snapshot encoding/decoding
