yorkie-team/yorkie-ios-sdk

- .github/workflows/swift.yml
- CONTRIBUTING.md
Run SwiftLint and SwiftFormat on CI.
Update CONTRIBUTING.md to add Code Style.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Update swift.yml to use SwiftLint

- Sources/Core/Client.swift
- Sources/Document/CRDT/Root.swift
- Sources/Document/Change/Change.swift
- Sources/Document/Json/Object.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Time/Ticket.swift
- Sources/Util/Heap.swift
- Yorkie.xcodeproj/project.pbxproj
Create folders based on yorkie-js-sdk
Git can not add empty folders so added empty files.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Create folders based on yorkie-js-sdk

- Package.swift
- Sources/Core/Client.swift
- Sources/Core/Logger.swift
- Tests/Core/ClientTests.swift
- Yorkie.xcodeproj/project.pbxproj
Add simple implementations of client activate/deactivate and test
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add client activate/deactivate

- .swiftlint.yml
- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/CRDT/CRDTElement.swift
- Sources/Document/CRDT/Primitive.swift
- Sources/Document/CRDT/RGATreeList.swift
- Sources/Document/CRDT/RHTPQMap.swift
- Sources/Document/Time/TimeTicket.swift
- Sources/Util/SplayTree.swift
- Tests/Document/CRDT/CRDTArrayTests.swift
- Tests/Document/CRDT/CRDTElementTests.swift
- Tests/Document/CRDT/RGATreeListTests.swift
- Tests/Document/Time/TimeTicketTests.swift
- Tests/Util/SplayTreeTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Add Array
- Change some method's names from delete to remove
- Change some methods from returning null to  throwing an error
- Change comparing methods of CRDTElement and TimeTicket
- Don't care about RHTPQMap.swift. I'll modify the file soon.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add CRDTArray

- .github/workflows/swift.yml
- .gitignore
Report the code coverage to codecov
Add lcov.info to .gitignore
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Report the code coverage to codecov

- .github/workflows/swift.yml
- Tests/API/V1/GRPCTests.swift
- Tests/Core/ClientTests.swift
- codecov.yml
This follows up #18.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Hyeongsik won fix/remove docker

- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/CRDT/CRDTElement.swift
- Sources/Document/CRDT/CRDTObject.swift
- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/CRDT/RGATreeList.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Operation/SetOperation.swift
- Sources/Document/Time/ActorId.swift
- Sources/Document/Time/TimeTicket.swift
- Tests/Document/CRDT/CRDTArrayTests.swift
- Tests/Document/CRDT/CRDTElementTests.swift
- Tests/Document/CRDT/CRDTObjectTests.swift
- Tests/Document/CRDT/CRDTRootTests.swift
- Tests/Document/CRDT/PrimitiveTests.swift
- Tests/Document/CRDT/RHTTests.swift
- Tests/Document/Operation/RemoveOperationTests.swift
- Tests/Document/Operation/SetOperationTests.swift
- Tests/Document/Time/TimeTicketTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Add CRDTRoot
- Add Operation, SetOperation and RemoveOepration
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add CRDTRoot, Operation, SetOperation and RemoveOepration

- Sources/Document/Operation/AddOperation.swift
- Sources/Document/Operation/MoveOperation.swift
- Tests/Document/Operation/AddOperationTests.swift
- Tests/Document/Operation/MoveOperationTests.swift
- Yorkie.xcodeproj/project.pbxproj
Implementd AddOperation and MoveOperation
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add AddOperation and MoveOperation

- Sources/Document/Json/Strings.swift
- Tests/Document/Json/StringEscapingTests.swift
- Yorkie.xcodeproj/project.pbxproj
Modified escaping string 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Modify escaping string

- .swiftlint.yml
- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/DocEvent.swift
- Sources/Document/Document.swift
- Sources/Document/Json/ElementConverter.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONDatable.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Util/Heap.swift
- Sources/Util/Optional+Extensions.swift
- Sources/Util/Trie.swift
- Tests/Document/CRDT/CRDTRootTests.swift
- Tests/Document/Change/ChangeIDTests.swift
- Tests/Document/Change/ChangeTests.swift
- Tests/Document/DocumentTests.swift
- Tests/Document/JSONArrayTests.swift
- Tests/Document/JSONObjectTests.swift
- Tests/Document/Operation/AddOperationTests.swift
- Tests/Document/Operation/MoveOperationTests.swift
- Tests/Document/Operation/RemoveOperationTests.swift
- Tests/Document/Operation/SetOperationTests.swift
- Yorkie.xcodeproj/project.pbxproj
Added JSONArrays and test codes.
Applied ```dynamicMemberLookup``` to  JSONObject
[Add eventStream to Document and DocType](https://github.com/yorkie-team/yorkie-ios-sdk/pull/27/commits/4e677f4d2f8329a8529da5c20331dd3cb4152739)
[Add unit tests for Document](https://github.com/yorkie-team/yorkie-ios-sdk/pull/27/commits/759ca5a5ece9854326784992dd2c5738d8a578f5)
[Fix bugs for Heap.delete](https://github.com/yorkie-team/yorkie-ios-sdk/pull/27/commits/908e3ec1b61fd872454700b9e004bc5df150ee57)
[Remove get(keyPath:) from JSONObject](https://github.com/yorkie-team/yorkie-ios-sdk/pull/27/commits/704aebce33293b2e9fb4ad8a28bb795ee5169dca)
[Fix bugs of JSONArray](https://github.com/yorkie-team/yorkie-ios-sdk/pull/27/commits/0597b010c1620b7f981c33fd3a3288fda96921 …
> Add JSONArrays and unit tests for Document

- Example/Example.xcworkspace/contents.xcworkspacedata
- Example/Example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/Example.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/ExampleApp/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp/ExampleApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Example/ExampleApp/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/ExampleApp/ExampleApp/AppDelegate.swift
- Example/ExampleApp/ExampleApp/Assets.xcassets/AccentColor.colorset/Contents.json
- Example/ExampleApp/ExampleApp/Assets.xcassets/AppIcon.appiconset/Contents.json
- Example/ExampleApp/ExampleApp/Assets.xcassets/Contents.json
- Example/ExampleApp/ExampleApp/Base.lproj/LaunchScreen.storyboard
- Example/ExampleApp/ExampleApp/Base.lproj/Main.storyboard
- Example/ExampleApp/ExampleApp/Info.plist
- Example/ExampleApp/ExampleApp/SceneDelegate.swift
- Example/ExampleApp/ExampleApp/ViewController.swift
- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/Json/JSONArray.swift
- Tests/Document/JSONArrayTests.swift
[Create ExampleApp](https://github.com/yorkie-team/yorkie-ios-sdk/commit/ab20b204a101738d1baa07bdcc6d107bbdbf9c70)
[Modify JSONArray/append to return the number of elements](https://github.com/yorkie-team/yorkie-ios-sdk/commit/37b40ad9fda3cfe0e25eea2e43bdff98a9daf819)
[Modify CRDTArray/toJSON use self for iteration](https://github.com/yorkie-team/yorkie-ios-sdk/commit/89bd3f232b18ef026ee842165582a4e76bf05944)
Created ExampleApp that can use the Yorkie framework. Currently, it does nothing, but we will use it to test the Yorkie framework.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Create ExampleApp and fix some bugs

- Sources/API/Converter.swift
- Sources/API/GRPCTypeAlias.swift
- Sources/Core/Client.swift
- Sources/Core/ClientEvent.swift
- Sources/Document/CRDT/RHTPQMap.swift
- Sources/Document/Change/ChangePack.swift
- Sources/Document/Document.swift
- Sources/Document/Time/TimeTicket.swift
- Sources/Util/Codable+Extension.swift
- Sources/Util/Errors.swift
- Tests/API/V1/ConverterTests.swift
- Tests/Core/ClientTests.swift
- Tests/Integration/ClientIntegrationTests.swift
- Yorkie.xcodeproj/project.pbxproj
- Implement full features of the client.
- Add Integration test for the client and the document.
Fixes #
- Due to CI status. All the tests related to the client have been skipped.
- ~~The auto-sync feature isn't working correctly.~~
```release-note
```
```docs
```
**Checklist**:
> Implement Client functions.

- Sources/Core/Client.swift
- Tests/Core/ClientTests.swift
- Tests/Integration/ClientIntegrationTests.swift
- Convert Client from class to actor for concurrency.
- Change the scheduling Timer method.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Convert Client from class to actor for concurrency.

- Sources/API/Converter.swift
- Sources/Document/CRDT/Primitive.swift
Fixes #
- Set the endian of primitive values to the value of the server (little endian) 
```release-note
```
```docs
```
**Checklist**:
> Change endian of Primitive values to little endian

- .github/workflows/add-release-assets.yml
- .github/workflows/gh-pages.yml
- Package.resolved
- Package.swift
- [Add a github action to publish API reference doc](https://github.com/yorkie-team/yorkie-ios-sdk/pull/41/commits/d2f61bac1d9195367f15e9aa58861078d7b216cf)
- The `github action` publishes API reference docs when a tag is pushed upstream.
- API reference docs URL: https://yorkie.dev/yorkie-ios-sdk/documentation/yorkie/
- [Add a github action to add API reference docs to rleases assets](https://github.com/yorkie-team/yorkie-ios-sdk/pull/41/commits/6426ff0ddaa21267b1db98c807ee34bc10aad838)
- Examples:
- Add swift-docc-plugin to Swift packages
Enabled pages setting of yorkie-ios-sdk.
Fixes #
```release-note
```
**Additional …
> Add a github action to publish API reference docs

- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/CRDT/CRDTElement.swift
- Sources/Document/CRDT/CRDTObject.swift
- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/CRDT/RGATreeList.swift
- Sources/Document/Change/ChangePack.swift
- Sources/Document/Change/Checkpoint.swift
- Sources/Document/DocEvent.swift
- Sources/Document/Document.swift
- Sources/Document/Operation/AddOperation.swift
- Sources/Document/Operation/MoveOperation.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Operation/SetOperation.swift
- Sources/Document/Util/JSONObjectable.swift
- Tests/Unit/Document/Operation/MoveOperationTests.swift
Apply changed comments of JS-SDK 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Apply changed comments of JS-SDK

- MAINTAINING.md
- Tests/Integration/CounterIntegrationTests.swift
Update CHANGELOG.md for v0.2.19
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Create MAINTAINING.md for v0.2.19

- Package.resolved
- Package.swift
- Sources/Core/Client.swift
- Sources/Core/Logger.swift
- Sources/Document/CRDT/CRDTArray.swift
- Sources/Document/CRDT/RGATreeList.swift
- Sources/Document/CRDT/RHT.swift
- Sources/Document/CRDT/RHTPQMap.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONCounter.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Document/Operation/AddOperation.swift
- Sources/Document/Operation/IncreaseOperation.swift
- Sources/Document/Operation/MoveOperation.swift
- Sources/Document/Operation/RemoveOperation.swift
- Sources/Document/Operation/SetOperation.swift
- Sources/Util/RedBlackTree.swift
- Yorkie.xcodeproj/project.pbxproj
- Yorkie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Apply swift-log package. (https://github.com/apple/swift-log.git)
- Changed the Logger to debug the GRPC issue.
- swift-log is a well-known swift package. and  GRPC uses that by logging.
- It's a more efficient way than using the print() function.
- change some log level 
-  trivial -> trace
- warn -> waring
-  fatal -> critical
- Updates all packages to the latest version.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Apply swift-log package.

- Examples/Example.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/KanbanApp/KanbanApp.xcodeproj/project.pbxproj
- Examples/KanbanApp/KanbanApp/Kanban/KanbanViewModel.swift
- Remove a "try" keyword by changing the Client's Interface.
- Now the example app uses the latest SDK in the main branch.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Change the client relate code in the Example.

- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/RHT.swift
- Sources/Document/Json/JSONText.swift
- Tests/Integration/TextIntegrationTests.swift
- Tests/Unit/Document/CRDT/CRDTTextTests.swift
- Tests/Unit/Document/CRDT/RHTTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- Modified to not display "attrs" with no value.
- Modified to not display node with no value. (eg. root value)
- Change parameters of setStyle() to match coding style
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Update toJson() of Text to match results with JS

- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/ClientTests.swift
- Tests/Integration/CounterIntegrationTests.swift
- Tests/Integration/TextIntegrationTests.swift
- Remove delays for sync in Test cases by using manual sync.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove delays for sync

- Examples/KanbanApp/KanbanApp/Kanban/View/KanbanLayoutProperty.swift
- Sources/Util/String+Extensions.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/CounterIntegrationTests.swift
- Tests/Integration/TextIntegrationTests.swift
Add toDocKey to convert to a valid key in tests.
Related to https://github.com/yorkie-team/yorkie/pull/467
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add toDocKey to convert to a valid key in tests

- Examples/TextEditorApp/TextEditorApp.xcodeproj/project.pbxproj
- Examples/TextEditorApp/TextEditorApp/TextEditor/TextViewModel.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/View/PeerSelectionDisplayLayoutManager.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/View/TextEditorViewController.swift
- Implement the select feature in the Text Editor
- Now Text editor can display selected blocks by peers.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Implement the select feature in the Text Editor

- Examples/TextEditorApp/TextEditorApp/TextEditor/TextViewModel.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/View/TextEditorViewController.swift
- Sources/Core/Client.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/CounterIntegrationTests.swift
- Tests/Integration/TextIntegrationTests.swift
- Implement the pause/resume functions.
- Pause the sync when the Hangul composition is started or the multistage input is started.
- Resume the sync when the Hangul composition is ended or the multistage input is ended.
- Detect the Hangul composition by monitoring input and composed characters by comparing with Unicode Hangul jamo.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Implement the pause/resume

- Sources/Core/Client.swift
- Tests/Integration/ClientIntegrationTests.swift
- iOS SDK already returns nil when searching for the presence of a non-existent peer. 
- So I refactored the codes that related to getPeerPresence() and Add a Test code for the presence of a non-existent peer.
- add getPresence() in the Attachment.
- rename getPeers() to getPeersByDocKey()  in the Client
- add getPeerPresence() in the Client
Fixes #75 
I'll change the target branch of the merge to the main after the previous PR is merged.
```release-note
```
```docs
```
**Checklist**:
> Fix when searching for presence of non-existent peer

- Sources/Version.swift
Fixes #
```release-note
```
```docs
```
**Checklist**:
> bump to 0.3.6

- Sources/Document/Json/JSONTree.swift
- expose `pathToIndex` api
- to let users to set selection by using path 
- https://github.com/yorkie-team/yorkie-js-sdk/pull/567
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Expose pathToIndex API

- Sources/Version.swift
- Tests/Unit/Util/Helper.swift
- Yorkie.xcodeproj/project.pbxproj
- Prepare to release 0.4.6
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Prepare 0.4.6

- Sources/Document/Operation/EditOperation.swift
- Sources/Document/Operation/Operation.swift
- Tests/Unit/Document/JSONTextTest.swift
Remove 'selectOpInfo' as it is no longer needed. (Related #104)
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove SelectOpInfo

- .swiftpm/xcode/xcshareddata/xcschemes/Yorkie.xcscheme
- Package.swift
- Sources/Util/IndexTree.swift
- Tests/Benchmark/DocumentBenchmarkTests.swift
Add Tree.Edit benchmark and improve performance and fix a bit of code to improve performance
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Add Tree.Edit benchmark and improve performance

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Operation/Operation.swift
- Sources/Document/Operation/TreeEditOperation.swift
- Tests/Integration/TreeIntegrationTests.swift
- Remove duplicated struct TreeNode 
- Fix == operation of TreeStyleOpInfo
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Remove TreeNode

- Sources/Util/Dictionary+Extension.swift
- Although the attribute is a string, It is not Encodable. In that case, convert it to a string manually.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix the conversion for attribute of Tree

- Examples/TextEditorApp/TextEditorApp/TextEditor/TextViewModel.swift
- Sources/Version.swift
- Prepare to release 0.4.7
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Prepare to release 0.4.7

- Sources/Document/Presence/Presence.swift
- Open clear function of Presence
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Open clear function of Presence

- Examples/TextEditorApp/TextEditorApp/TextEditor/View/PeerSelectionDisplayLayoutManager.swift
- Examples/TextEditorApp/TextEditorApp/TextEditor/View/TextEditorViewController.swift
- Sources/Core/Client.swift
- Sources/Document/CRDT/CRDTObject.swift
- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RGATreeSplit.swift
- Sources/Document/CRDT/RHT.swift
- Sources/Document/Document.swift
- Sources/Document/Json/JSONArray.swift
- Sources/Document/Json/JSONObject.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Operation/TreeEditOperation.swift
- Sources/Util/Dictionary+Extension.swift
- Sources/Util/IndexTree.swift
- Tests/Integration/GCTests.swift
- Tests/Unit/Document/CRDT/CRDTTreeTests.swift
- Tests/Unit/Util/Helper.swift
- It's iOS implementation for PR of JS below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/686
- By lint by the swiftformat, forEach is converted to for loop. 
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Refactor Tree codes

- Sources/Document/CRDT/CRDTTree.swift
- It's iOS implementation for PR of JS below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/709
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Support concurrent insertion and splitting in Tree

- .swiftlint.yml
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Util/IndexTree.swift
- Tests/Integration/TreeIntegrationTests.swift
- Tests/Unit/Util/IndexTreeTests.swift
- docker/docker-compose-ci.yml
- docker/docker-compose.yml
- It's iOS implementation for PR of JS below.
- https://github.com/yorkie-team/yorkie-js-sdk/pull/712
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Generate correct TreeChange in concurrent edits

- Sources/Version.swift
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Bump to 0.4.12

- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Tests/Integration/TreeIntegrationTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/742
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix incorrect index returned when using posRangeToIndexRange

- Sources/API/Converter.swift
- Sources/Document/CRDT/CRDTText.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/CRDT/RGATreeSplit.swift
- Sources/Document/Change/ChangeID.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Document/Time/TimeTicket.swift
- Tests/Unit/Document/Change/ChangeContextTests.swift
- Tests/Unit/Document/Change/ChangeIDTests.swift
- Tests/Unit/Document/Change/ChangePackTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/747
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Change actorID to be non-optional

- Sources/Document/Document.swift
- Tests/Integration/ClientIntegrationTests.swift
- Tests/Integration/DocumentIntegrationTests.swift
- Tests/Integration/IntegrationHelper.swift
- Tests/Integration/PresenceTests.swift
- Tests/Integration/TreeIntegrationTests.swift
- Tests/Unit/Document/DocumentTests.swift
- Tests/Unit/Document/JSONTextTest.swift
- Modified to enable async closure in Subscription callback.
- Add the document parameter to the Subscription callback.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Modified to enable async closure in Subscription callback.

- Sources/API/Converter.swift
- Sources/Document/CRDT/CRDTTree.swift
- Sources/Document/Json/JSONTree.swift
- Sources/Util/IndexTree.swift
- Tests/Integration/TreeIntegrationTests.swift
- Tests/Unit/Document/DocumentConcurrentAccessTests.swift
- Change String from swift String to NSString to support UTF16 string.
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix Tree to support emoji chracters.

- .github/workflows/swift.yml
Provide CODECOV_TOKEN to codecov-action
Fixes #
https://github.com/yorkie-team/yorkie-ios-sdk/actions/runs/8659763624/job/23746307969#step:8:31
```release-note
```
```docs
```
**Checklist**:
> Provide CODECOV_TOKEN to codecov-action

- Sources/Document/CRDT/CRDTRoot.swift
- Sources/Document/Document.swift
- Tests/Benchmark/DocumentBenchmarkTests.swift
- Tests/Integration/GCTests.swift
- Tests/Unit/Document/DocumentTests.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/806
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix inconsistent garbage collection for multiple nodes in text and tree type

- Sources/Document/CRDT/CRDTTree.swift
- https://github.com/yorkie-team/yorkie-js-sdk/pull/830
Fixes #
```release-note
```
```docs
```
**Checklist**:
> Fix invalid error message in CRDTTreePos
